"""Batch Generate enqueue planning.

Pure planning: given a category + count, resolve which products get cards, one
per color, with a composed prompt — and collect a reason for every product that
is skipped (no drive folder, no images, no prompt). Does not touch the DB writer
or the worker; the router persists ``rows`` and kicks the worker.
"""

from __future__ import annotations

from mockup_generator.db import batch_items_repo as repo
from mockup_generator.db import products_repo, prompts_repo, variants_repo
from mockup_generator.integrations import drive_client
from mockup_generator.prompts.defaults import prompt_for_category

_PREFIX_COLOR = "Make the professional mockup of the {color} product."
_PREFIX_PLAIN = "Make the professional mockup of the product."

# Products with more folders' worth of source images than this are left out of
# the batch and generated by hand instead — picking which of many shots to feed
# the model is a judgement call, and a card that guesses wastes a generation.
_MAX_SOURCE_IMAGES = 5


def compose_prompt(color: str | None, body: str) -> str:
    prefix = _PREFIX_COLOR.format(color=color) if color else _PREFIX_PLAIN
    return f"{prefix}\n\n{body}"


def resolve_category_prompt(db, categoryid: str) -> str | None:
    """DB default -> hardcoded CATEGORY_PROMPTS -> None."""
    for p in prompts_repo.list_by_category(db, categoryid):
        if p.is_default:
            return p.body
    return prompt_for_category(categoryid)


def _card_rows(
    db, p, *, model: str, resolution: str, aspect_ratio: str,
    batch_id: str, created_by: str | None,
) -> tuple[list[dict], str | None]:
    """Cards for one product (one per colour), or ``([], reason)`` if it can't be
    generated. Does not check for an existing un-reviewed card — the caller does
    that in a batched query."""
    body = resolve_category_prompt(db, p.categoryid)
    if not body:
        return [], f"no prompt for category {p.categoryid}"
    folder_id = drive_client.extract_folder_id(p.producturl)
    if not folder_id:
        return [], "no drive folder"
    # Ask for one more than allowed: a full slate proves the product is over the
    # limit without paging the whole folder, and anything short of it is already
    # the complete set to generate from.
    image_ids = drive_client.list_folder_image_ids(folder_id, limit=_MAX_SOURCE_IMAGES + 1)
    if not image_ids:
        return [], "no images"
    if len(image_ids) > _MAX_SOURCE_IMAGES:
        return [], f"more than {_MAX_SOURCE_IMAGES} images — generate manually"
    colors = variants_repo.list_colors(db, p.productid) or [None]
    return [
        {
            "batch_id": batch_id,
            "productid": p.productid,
            "color": color,
            "image_ids": image_ids,
            "prompt_text": compose_prompt(color, body),
            "status": repo.QUEUED,
            "model": model,
            "resolution": resolution,
            "aspect_ratio": aspect_ratio,
            "created_by": created_by,
        }
        for color in colors
    ], None


def plan_cards(
    db, *, category: str | None, count: int, model: str, resolution: str,
    aspect_ratio: str, batch_id: str, created_by: str | None,
) -> tuple[list[dict], list[dict]]:
    """Plan cards for up to ``count`` products. Products with an un-reviewed card
    (queued/generating/ready) or that can't be generated are skipped, and the
    next pending products are pulled in to backfill the target — so re-running a
    batch keeps making forward progress instead of stalling on the same rows."""
    rows: list[dict] = []
    skipped: list[dict] = []
    enqueued = 0
    offset = 0
    # Page wide enough that a run of skips doesn't cost one query per product.
    page_size = max(count, 20)

    while enqueued < count:
        products = products_repo.list_products(
            db, category=category, pending=True, limit=page_size, offset=offset)
        if not products:
            break  # pending pool exhausted before reaching count
        offset += len(products)
        # Don't regenerate a product that already has an un-reviewed card waiting
        # in the queue or in Ready — accept or reject it first.
        active = repo.active_productids(db, [p.productid for p in products])

        for p in products:
            if enqueued >= count:
                break
            if p.productid in active:
                skipped.append({"productid": p.productid, "reason": "already queued or awaiting review"})
                continue
            product_rows, reason = _card_rows(
                db, p, model=model, resolution=resolution, aspect_ratio=aspect_ratio,
                batch_id=batch_id, created_by=created_by)
            if reason:
                skipped.append({"productid": p.productid, "reason": reason})
                continue
            rows.extend(product_rows)
            enqueued += 1

    return rows, skipped
